//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0241506_EczCVEntities : DbContext
    {
        public u0241506_EczCVEntities()
            : base("name=u0241506_EczCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deneyim> Deneyim { get; set; }
        public virtual DbSet<Egitim> Egitim { get; set; }
        public virtual DbSet<Sertifika> Sertifika { get; set; }
        public virtual DbSet<Yetenek> Yetenek { get; set; }
        public virtual DbSet<CVAdmin> CVAdmin { get; set; }
        public virtual DbSet<Hobi> Hobi { get; set; }
        public virtual DbSet<Proje> Proje { get; set; }
        public virtual DbSet<Kimlik> Kimlik { get; set; }
    }
}
